name: Tests
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]

    # Service containers to run with `runner-job`
    services:
      nats:
        image: nats
        ports:
          - 4223:4222
      nats-auth:
        image: ghcr.io/overmindtech/test-populated-nats:main
        ports:
          - 4222:4222

      api-server:
        image: ghcr.io/overmindtech/test-populated-api-server:main
        env:
          # This is the URL of the nats-auth container above. Thankfully github
          # creates all service containers on the same network, and with a nice
          # network alias so we can use docker-provided DNS to have them talk to
          # one another
          NATS_URL: nats://nats-auth:4222
          DISABLE_KUBE: true
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.x

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Vet
        run: go vet

      - name: Test
        run: go test -race -timeout 5m -v ./...
        env:
          OVERMIND_NTE_ALLPERMS_DOMAIN: ${{ secrets.OVERMIND_NTE_ALLPERMS_DOMAIN }}
          OVERMIND_NTE_ALLPERMS_CLIENT_ID: ${{ secrets.OVERMIND_NTE_ALLPERMS_CLIENT_ID }}
          OVERMIND_NTE_ALLPERMS_CLIENT_SECRET: ${{ secrets.OVERMIND_NTE_ALLPERMS_CLIENT_SECRET }}

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    steps:
      # Creates a release and attaches
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
