name: Tests
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      nats:
        image: nats
        ports:
          - 4223:4222
      nats-auth:
        image: ghcr.io/overmindtech/test-populated-nats:main
        ports:
          - 4222:4222
      nats-token-exchange:
        image: ghcr.io/overmindtech/test-populated-nats-token-exchange:main
        ports:
          - 8080:8080
      dgraph:
        image: dgraph/standalone
        ports:
          - 9080:9080
        
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod vendor -v 
    
      - name: Build
        run: go build -v .

      - name: Test
        env:
          OVERMIND_NTE_ALLPERMS_DOMAIN: dev-qsurrmp8.eu.auth0.com
          OVERMIND_NTE_ALLPERMS_CLIENT_ID: tLETA8lsQZR4p2qxILB1kKoXjqGJTPlG
          OVERMIND_NTE_ALLPERMS_CLIENT_SECRET: ${{ secrets.OVERMIND_NTE_ALLPERMS_CLIENT_SECRET }}
        run: go test -race -timeout 5m -v ./...

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    steps:
      # Creates a release and attaches
      - name: Create Release
        uses: ncipollo/release-action@latest
        with:
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
